=== albfan/diffmk/lib/diffmk.dtd
<!ELEMENT diffmk (doctype*)>
<!ATTLIST diffmk
	xmlns		CDATA	#FIXED
				"http://www.sun.com/xml/diffmk"
	xmlns:xsi	CDATA	#FIXED
				"http://www.w3.org/2000/10/XMLSchema-instance"
	xsi:schemaLocation	CDATA	#IMPLIED
>

<!ELEMENT doctype ((root|wrapper|verbatim|ignoreattribute)*)>
<!ATTLIST doctype
	name		CDATA	#REQUIRED
	attribute	CDATA	#IMPLIED
	changed		CDATA	#IMPLIED
	added		CDATA	#IMPLIED
	deleted		CDATA	#IMPLIED
>

<!ELEMENT root EMPTY>
<!ATTLIST root
	name		CDATA	#REQUIRED
	ns		CDATA	#IMPLIED
>

<!ELEMENT wrapper EMPTY>
<!ATTLIST wrapper
	parent		CDATA	#IMPLIED
	element		CDATA	#IMPLIED
>

<!ELEMENT verbatim EMPTY>
<!ATTLIST verbatim
	element		CDATA	#IMPLIED
>

<!ELEMENT ignoreattribute EMPTY>
<!ATTLIST ignoreattribute
	element		CDATA	#IMPLIED
	name		CDATA	#IMPLIED
>

=== albfan/diffmk/lib/diffmk.xml
<?xml version='1.0'?>
<!DOCTYPE diffmk SYSTEM "diffmk.dtd">
<diffmk xmlns='http://www.sun.com/xml/diffmk'
        xmlns:xsi='http://www.w3.org/2000/10/XMLSchema-instance'
        xsi:schemaLocation='http://www.sun.com/xml/diffmk
                            diffmk.xsd'>

<doctype name="docbook"
         attribute="revisionflag"
         changed="changed"
         added="added"
         deleted="deleted">
  <root name="book"/>
  <root name="article"/>
  <root name="chapter"/>
  <root name="appendix"/>
  <root name="para"/>
  <wrapper element="phrase"/>
  <wrapper parent="article" element="para"/>
  <wrapper parent="section" element="para"/>
  <wrapper parent="sect1" element="para"/>
  <wrapper parent="sect2" element="para"/>
  <wrapper parent="sect3" element="para"/>
  <wrapper parent="sect4" element="para"/>
  <wrapper parent="sect5" element="para"/>
  <wrapper parent="refsect1" element="para"/>
  <wrapper parent="refsect2" element="para"/>
  <wrapper parent="refsect3" element="para"/>
  <wrapper parent="pubdate"/>
  <wrapper parent="releaseinfo"/>
  <wrapper parent="sgmltag"/>
  <wrapper parent="revision"/>
  <wrapper parent="revnumber"/>
  <wrapper parent="date"/>
  <wrapper parent="revremark"/>
  <wrapper parent="authorinitials"/>
  <wrapper parent="literal"/>
  <wrapper parent="replaceable"/>
</doctype>

<doctype name="xmlspec"
         attribute="diff"
         changed="chg"
         added="add"
         deleted="del">
  <root name="spec"/>
  <wrapper element="phrase"/>
  <wrapper parent="status" element="p"/>
  <wrapper parent="div1" element="p"/>
  <wrapper parent="div2" element="p"/>
  <wrapper parent="div3" element="p"/>
  <wrapper parent="div4" element="p"/>
  <wrapper parent="div5" element="p"/>
  <wrapper parent="inform-div1" element="p"/>
  <wrapper parent="back" element="p"/>
  <wrapper parent="w3c-designation"/>
  <wrapper parent="item" element="p"/>
  <wrapper parent="el"/>
  <wrapper parent="day"/>
  <wrapper parent="month"/>
  <wrapper parent="year"/>
  <wrapper parent="loc"/>
  <wrapper parent="code"/>
  <wrapper parent="version"/>
  <wrapper parent="authlist"/>
  <wrapper parent="copyright"/>
  <wrapper parent="header"/>
  <verbatim element="eg"/>
  <verbatim element="bnf"/>
</doctype>

<doctype xmlns:x="http://www.w3.org/1999/xhtml"
         name="xhtml"
         attribute="class"
         changed="chg"
         added="add"
         deleted="del">
  <root name="x:html"/>
  <wrapper element="span"/>
  <wrapper parent="body" element="div"/>
</doctype>

<doctype name="dtd"
         attribute="diff"
         changed="chg"
         added="add"
         deleted="del">
  <root name="dtd"/>
  <ignoreattribute element="dtd" name="*"/>
</doctype>

</diffmk>
